cache:
  directories:
    - $HOME/.m2

language: java

services:
  - docker

stages:
  - test
  - deploy

before_install:
  - chmod +x mvnw

install: skip

jobs:
  include:
    - stage: test
      name: "Testing Application"
      services: postgresql
      before_script:
        - psql -c 'CREATE DATABASE app_test;' -U postgres
      script:
        - make test

    - stage: deploy
      name: "Deploy Application to Production"
      script:
        - make deploy